### ISSUE TITLE
Half-working: what to do?

### ISSUE THREAD

**Issue by Vistaus** [vera-desktop/vera#4]
I've compiled all of the necessary stuff with all of the dependencies installed but when launching Vera from GDM I get a half-working DE. It did show the tutorial at first boot but with a black screen. Now it does show something but there are no titlebars, no right mouse click menu on the desktop, the launcher works but a bit buggy.

OS: Antergos (based on Arch) with GDM 3.16

What to do?

**Comment by g7** [comment]
Hello Vistaus (and thank you for the always-updated Dutch translations, they are really appreciated! :D),

Which plugins did you compile? The menu is still handled by Openbox, so you need vera-plugin-openbox and our openbox menu framework (https://github.com/semplice/alan2).

If the launcher is working but you see a black screen it's probably just the missing wallpaper. Try changing it via the control center.

Also, please post the content of ~/.xsession-errors.

Thanks,
Eugenio

**Comment by Vistaus** [comment]
Hello,

sorry for my late reply! :(

No problem, I love translating :D 

I've compiled alan2, vera-plugin-openbox, vera-desktop, vera-control-center, vera-plugin-desktop, vera-plugin-power, vera-power-manager and vera-xsettings.

.xsession-errors doesn't exist on my system :/

**Comment by g7** [comment]
It seems to me that Openbox wasn't correctly configured by vera.
Do you have the ~/.config/vera/openbox directory? If yes, are there some files or it's empty?

Please also post the output of
```
alan-config -p vera -i ~/.config/vera -l
```

Eugenio

**Comment by Vistaus** [comment]
Uunfortanetly, something went wrong with my computer so I don't have access to Arch anymore. I've ordered a new one and I'll install the full Semplice on it! :-)

Thanks for the great help though! :-)
